# Generated by Django 5.2.7 on 2025-11-01 17:09

import uuid
from django.db import migrations, models

import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=20, null=True, unique=True
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("partner", "Partner"),
                            ("internal", "Internal"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        # Add composite index on source and created_at
        migrations.AddIndex(
            model_name="professional",
            index=models.Index(
                fields=["source", "-created_at"],
                name="prof_source_created_idx",
            ),
        ),
    ]
